apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: {{ .Values.redis.service.protocol }}
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}

