apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
    - protocol: {{ .Values.web.service.protocol }}
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
  type: NodePort


